language: java
jdk:
  - openjdk8
notification:
  email:
    recipients:
      - wzs2009_hi@126.com
    on_success: always
    on_failure: always

before_install:
  - pip install --user codecov

after_success:
  - mvn clean test jacoco:report coveralls:report
  - codecov

branches:
  only:
    - master

env:
  global:
    - secure: "hBtssC21H39GYQfZJF70QGIOGOeb6vNehswEzTWRUrvgbz2nRyuqlb4X6jBA7Q4vPiALitW3zpBw4UbvuXyc8w+HPmNDq1uMl0Zha7lVpYjcJeqSptZrolwdiQrEZdl17RlW2ljCf9Ub4Zsvo3Yhad4pWZGiOn9btbrTn/gUGK/xQsDhJURF+Vt1pYUK7WzEt7cf6wO9YcvueXQcBImkcwHYzl1mAtsie5Tz4zGYEBUYtcddUMAWZrlrDyv8UcQvgXlTanLCP6+wHPbIrqjCnYfG9Y4gRheNI3uq/gHGS5SIdWxXq2QstGMNj9rBa/PyjzpPp2OiDPVyVs+/5B3M9ta10eiNrWhVPqJdOj4fWjBfiXqSaEoaAVh3yEE2i2Ixbut3E0JG3PSAOnsZhujSXwZWVb2Pm07C0z+G5NxOCqTUopl2fCFNCjAhBCQtLpACQp4aphGoTPyCGViMr9hXqvihxtG0meWsLEplQJ2diE0Xw+6OENjgQm1HhWITv2JEDUxExL/wd1WLmZb3M62xDmh8WCxjEyWgodHpnr/zwqdOVq4/7rRewrZMaZuLXtyAa/Nd54snrjQ+xk1PN9IQs/zQJHDwanHANJtrGqtr3XVl2oNvpIE8++U+J8YEFIFNnqDnUa753XXyTgts7yRN808B/r4hD4JdJeG+Iw7gTo0="
    - "MAVEN_OPTS=-Xms1024m -Xmx3072m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=384m"
before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "idefav/spring-boot-starter-rest-lb"
      description: "Build submitted via Travis CI"
    notification_email: "wzs2009_hi@126.com"
    build_command_prepend: "mvn clean"
    build_command: "mvn -DskipTests=true compile"
    branch_pattern: master

cache:
  directories:
    - $HOME/.m2
